name: 🪲 Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug 🪲! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: Describe what happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Create a request with...
        2. Call fetch with...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Snippet
      description: Relevant code that demonstrates the issue
      render: typescript

  - type: input
    id: version
    attributes:
      label: "`fx-fetch` Version"
      placeholder: e.g., 1.1.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running `fx-fetch`?
      options:
        - Chromium-based browser
        - Safari
        - Firefox
        - NodeJS
        - Deno
        - Bun
        - Other
    validations:
      required: true
  
  - type: input
    id: environment_version
    attributes:
      label: Environment Version
      description: Version of the environment (e.g., browser version, NodeJS version)
      placeholder: e.g., 18.0.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
