name: 💡 Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like
      placeholder: Describe the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Use Case / Motivation
      description: Why would this feature be useful? What problem does it solve?
      placeholder: Explain the use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how this could be implemented
      placeholder: Describe your proposed solution (optional)

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered
      placeholder: Describe alternatives (optional)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, code examples, or screenshots
